### ISSUE TITLE
PI names in AWS drop down menu

### ISSUE THREAD

**Issue by saurabh-mk** [dilawar/ncbs-hippo#3]
1. Can there be a custom option for TCM members outside NCBS/inStem campus?
2. The PI names are ordered alphabetically, some by name or some by surname. But the name is always displayed as first name, last name. It might be a little difficult to find some names like this.

For example:
Sandeep Krushna
Sanjay Sane
**Apurva Sarin**
Shachi Gosavi...

Sunil Laxman
**Mukund Thattai**
Tina Mukherjee

**Comment by dilawar** [comment]
User can now add missing faculty while editing his/her AWS details. Supervisor 1 can not be from outside NCBS.

**Comment by dilawar** [comment]
Seems like sorting issue has been fixed by some other commit. I am closing it now. Let me know if you see the sorting according to mail id instead of first name.

**Comment by saurabh-mk** [comment]
1. It was already sorted by mail id I think. But it results in a non-alphabetical order of first/second names. It would be nice to order it by first name or second name consistently, rather than mail id, because the name is what is displayed.
2. If you give them a chance to add any name, someone will for sure inadvertently add a name that already exists. This will create downstream problems with collecting metadata or sorting. Can it be made sure that only those names that do not exist are added?

**Comment by dilawar** [comment]
External PIs are identified by their email id which is mandatory. If a duplicate email id is entered, it will be ignored. So each entry is uniquely determined by email ids.

The admin can edit/add new entries. Ideally all external PIs should be handled by admin. May be the user can request to add a PI which can be approved by the admin. 

For time being I'll let anyone add external PI. Later, the user can only request to add PI which must be peer reviewed.

**Comment by dilawar** [comment]
I think this has been fixed. Open it if you notice something out of plce.
