### ISSUE TITLE
Authentication problem when going to index after login 

### ISSUE THREAD

**Issue by rohitsuratekar** [dilawar/ncbs-hippo#8]
You will get sign out if you go to index at any time after login. You will get following error in such case,

<img width="815" alt="untitled" src="https://cloud.githubusercontent.com/assets/8757115/22723464/a06cf164-ede4-11e6-8cf3-9e69f73d9dc5.png">

**Comment by dilawar** [comment]
Seems like the user was not authenticated properly. It shows 'Hi anonymous' on right. That said,  ideally once logged-in and unless logged-out, going to index.php page should redirect to 'user.php' page.
